import { Card } from "./card";

export class CardRepository{
  private cards:Card[];

  constructor() {

    this.cards=[

      {id:1,imageUrl:"../../assets/Images/blog-projesi-6.jpg",title:"html Lorem, ipsum dolor.",description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit  Dolorum labore numquam excepturi unde architecto expedita quod accusamus repudiandae eum magni dolorem nobis sint commodi voluptatum accusantium, molestiae cupiditate iusto possimus Corporis temporibus reiciendis ullam maiores natus. Magnam inventore consectetur natus minus! In doloribus vero non, ut veritatis optio, sequi quod repudiandae impedit excepturi iure similique blanditiis illo maiores possimus sunt Incidunt dolore reiciendis, unde ullam atque sunt odit, fugiat pariatur fugit quo debitis. A facilis, laudantium asperiores sapiente voluptatem, fugiat magnam debitis at molestias adipisci ullam necessitatibus reprehenderit. Accusantium, culpa.Doloribus voluptas sed possimus aut accusantium temporibus consequatur natus, eveniet quas? Ut, et dicta laboriosam facilis nostrum veritatis molestiae praesentium inventore totam? Quos autem temporibus praesentium? Nostrum vero accusamus ea. Qui minus officiis fugit quaerat id quam corporis architecto sunt suscipit! Alias, sit    dicta dolorum laborum error necessitatibus tempora sequi ad doloremque assumenda  dignissimos. Impedit vitae veniam eum nulla enim.",datePublished:new Date(2022,2,15),category:"HTML",views:0,comments:0,isPopular:true},
      {id:2,imageUrl:"../../assets/Images/blog-projesi-5.jpg",title:"html Lorem, ipsum dolor.",description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit  Dolorum labore numquam excepturi unde architecto expedita quod accusamus repudiandae eum magni dolorem nobis sint commodi voluptatum accusantium, molestiae cupiditate iusto possimus Corporis temporibus reiciendis ullam maiores natus. Magnam inventore consectetur natus minus! In doloribus vero non, ut veritatis optio, sequi quod repudiandae impedit excepturi iure similique blanditiis illo maiores possimus sunt Incidunt dolore reiciendis, unde ullam atque sunt odit, fugiat pariatur fugit quo debitis. A facilis, laudantium asperiores sapiente voluptatem, fugiat magnam debitis at molestias adipisci ullam necessitatibus reprehenderit. Accusantium, culpa.Doloribus voluptas sed possimus aut accusantium temporibus consequatur natus, eveniet quas? Ut, et dicta laboriosam facilis nostrum veritatis molestiae praesentium inventore totam? Quos autem temporibus praesentium? Nostrum vero accusamus ea. Qui minus officiis fugit quaerat id quam corporis architecto sunt suscipit! Alias, sit    dicta dolorum laborum error necessitatibus tempora sequi ad doloremque assumenda  dignissimos. Impedit vitae veniam eum nulla enim.",datePublished:new Date(2022,2,15),category:"CSS",views:0,comments:0,isPopular:true},
      {id:3,imageUrl:"../../assets/Images/blog-projesi-4.jpg",title:"html Lorem, ipsum dolor.",description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit  Dolorum labore numquam excepturi unde architecto expedita quod accusamus repudiandae eum magni dolorem nobis sint commodi voluptatum accusantium, molestiae cupiditate iusto possimus Corporis temporibus reiciendis ullam maiores natus. Magnam inventore consectetur natus minus! In doloribus vero non, ut veritatis optio, sequi quod repudiandae impedit excepturi iure similique blanditiis illo maiores possimus sunt Incidunt dolore reiciendis, unde ullam atque sunt odit, fugiat pariatur fugit quo debitis. A facilis, laudantium asperiores sapiente voluptatem, fugiat magnam debitis at molestias adipisci ullam necessitatibus reprehenderit. Accusantium, culpa.Doloribus voluptas sed possimus aut accusantium temporibus consequatur natus, eveniet quas? Ut, et dicta laboriosam facilis nostrum veritatis molestiae praesentium inventore totam? Quos autem temporibus praesentium? Nostrum vero accusamus ea. Qui minus officiis fugit quaerat id quam corporis architecto sunt suscipit! Alias, sit    dicta dolorum laborum error necessitatibus tempora sequi ad doloremque assumenda  dignissimos. Impedit vitae veniam eum nulla enim.",datePublished:new Date(2022,2,15),category:"BOOTSTRAP",views:0,comments:0,isPopular:true},
      {id:4,imageUrl:"../../assets/Images/blog-projesi-3.jpg",title:"html Lorem, ipsum dolor.",description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit  Dolorum labore numquam excepturi unde architecto expedita quod accusamus repudiandae eum magni dolorem nobis sint commodi voluptatum accusantium, molestiae cupiditate iusto possimus Corporis temporibus reiciendis ullam maiores natus. Magnam inventore consectetur natus minus! In doloribus vero non, ut veritatis optio, sequi quod repudiandae impedit excepturi iure similique blanditiis illo maiores possimus sunt Incidunt dolore reiciendis, unde ullam atque sunt odit, fugiat pariatur fugit quo debitis. A facilis, laudantium asperiores sapiente voluptatem, fugiat magnam debitis at molestias adipisci ullam necessitatibus reprehenderit. Accusantium, culpa.Doloribus voluptas sed possimus aut accusantium temporibus consequatur natus, eveniet quas? Ut, et dicta laboriosam facilis nostrum veritatis molestiae praesentium inventore totam? Quos autem temporibus praesentium? Nostrum vero accusamus ea. Qui minus officiis fugit quaerat id quam corporis architecto sunt suscipit! Alias, sit    dicta dolorum laborum error necessitatibus tempora sequi ad doloremque assumenda  dignissimos. Impedit vitae veniam eum nulla enim.",datePublished:new Date(2022,2,15),category:"JAVASCRIPT",views:0,comments:0,isPopular:true},
      {id:5,imageUrl:"../../assets/Images/blog-projesi-2.jpg",title:"html Lorem, ipsum dolor.",description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit  Dolorum labore numquam excepturi unde architecto expedita quod accusamus repudiandae eum magni dolorem nobis sint commodi voluptatum accusantium, molestiae cupiditate iusto possimus Corporis temporibus reiciendis ullam maiores natus. Magnam inventore consectetur natus minus! In doloribus vero non, ut veritatis optio, sequi quod repudiandae impedit excepturi iure similique blanditiis illo maiores possimus sunt Incidunt dolore reiciendis, unde ullam atque sunt odit, fugiat pariatur fugit quo debitis. A facilis, laudantium asperiores sapiente voluptatem, fugiat magnam debitis at molestias adipisci ullam necessitatibus reprehenderit. Accusantium, culpa.Doloribus voluptas sed possimus aut accusantium temporibus consequatur natus, eveniet quas? Ut, et dicta laboriosam facilis nostrum veritatis molestiae praesentium inventore totam? Quos autem temporibus praesentium? Nostrum vero accusamus ea. Qui minus officiis fugit quaerat id quam corporis architecto sunt suscipit! Alias, sit    dicta dolorum laborum error necessitatibus tempora sequi ad doloremque assumenda  dignissimos. Impedit vitae veniam eum nulla enim.",datePublished:new Date(2022,2,15),category:"JQUERY",views:0,comments:0,isPopular:true},
      {id:6,imageUrl:"../../assets/Images/blog-projesi-1.jpg",title:"html Lorem, ipsum dolor.",description:"Lorem ipsum dolor sit amet consectetur, adipisicing elit  Dolorum labore numquam excepturi unde architecto expedita quod accusamus repudiandae eum magni dolorem nobis sint commodi voluptatum accusantium, molestiae cupiditate iusto possimus Corporis temporibus reiciendis ullam maiores natus. Magnam inventore consectetur natus minus! In doloribus vero non, ut veritatis optio, sequi quod repudiandae impedit excepturi iure similique blanditiis illo maiores possimus sunt Incidunt dolore reiciendis, unde ullam atque sunt odit, fugiat pariatur fugit quo debitis. A facilis, laudantium asperiores sapiente voluptatem, fugiat magnam debitis at molestias adipisci ullam necessitatibus reprehenderit. Accusantium, culpa.Doloribus voluptas sed possimus aut accusantium temporibus consequatur natus, eveniet quas? Ut, et dicta laboriosam facilis nostrum veritatis molestiae praesentium inventore totam? Quos autem temporibus praesentium? Nostrum vero accusamus ea. Qui minus officiis fugit quaerat id quam corporis architecto sunt suscipit! Alias, sit    dicta dolorum laborum error necessitatibus tempora sequi ad doloremque assumenda  dignissimos. Impedit vitae veniam eum nulla enim.",datePublished:new Date(2022,2,15),category:"ANGULAR",views:0,comments:0,isPopular:true},


    ]

   }

   getCards():Card[]{
     return this.cards;
   }

   getCardById(id:number):Card{
     return this.cards.find(i=>i.id==id)
   }

   getPopularCards():Card[]{
     return this.cards.filter(i=>i.isPopular==true)
   }
}
